name: supertuxkart
version: '1.4'
adopt-info: supertuxkart

grade: stable
confinement: strict
base: core22

layout:
  /usr/share/libdrm:
    bind: $SNAP/usr/share/libdrm

apps:
  supertuxkart:
    extensions: [gnome]
    command: usr/bin/supertuxkart
    desktop: usr/share/applications/supertuxkart.desktop
    common-id: supertuxkart.desktop
    environment:
      SUPERTUXKART_DATADIR: $SNAP/usr/share/supertuxkart
    plugs:
    - audio-playback
    - bluetooth-control
    - joystick
    - network
    - network-bind
    - pulseaudio
    - screen-inhibit-control
  
parts:
  supertuxkart:
    plugin: cmake
    source: https://github.com/supertuxkart/stk-code/releases/download/$SNAPCRAFT_PROJECT_VERSION/SuperTuxKart-$SNAPCRAFT_PROJECT_VERSION-src.tar.xz
    override-pull: |
      snapcraftctl pull
      sed -i 's|^Icon=.*|Icon=/usr/share/icons/hicolor/128x128/apps/supertuxkart.png|' data/supertuxkart.desktop
    parse-info: [usr/share/metainfo/supertuxkart.appdata.xml]
    cmake-parameters:
    - -DCMAKE_INSTALL_PREFIX=/usr
    - -DENABLE_WAYLAND_DEVICE=ON
    - -DBUILD_RECORDER=OFF
    build-environment:
    - CFLAGS: -O2 -pipe
    - CXXFLAGS: -O2 -pipe
    build-packages:
    - curl
    - libbluetooth-dev
    - libcurl4-openssl-dev
    - libfreetype-dev
    - libfribidi-dev
    - libjpeg-dev
    - libogg-dev
    - libopenal-dev
    - libpng-dev
    - libpulse-dev
    - libsdl2-dev
    - libssl-dev
    - libvorbis-dev
    - libxrandr-dev
    - libxkbcommon-dev
    - subversion
    - zlib1g-dev
    stage-packages:
    - libbluetooth3
    - libcurl4
    - libdb5.3
    - libfreetype6
    - libfribidi0
    - libjpeg8
    - libogg0
    - libopenal1
    - libpng16-16
    - libpulse0
    - libsdl2-2.0-0
    - libssl3
    - libvorbis0a
    - libvorbisfile3
    - libxrandr2
    - libxkbcommon0
    - zlib1g

  cleanup:
    after: [supertuxkart]
    plugin: nil
    build-snaps: [core22, gtk-common-themes, gnome-42-2204]
    override-prime: |
      set -eux
      for snap in "core22" "gtk-common-themes" "gnome-42-2204"; do
          cd "/snap/$snap/current" && find . -type f,l -name *.so.* -exec rm -f "$CRAFT_PRIME/{}" \;
      done
