name: supertuxkart
version: '1.5'
adopt-info: supertuxkart

grade: stable
confinement: strict
base: core24

layout:
  /usr/share/libdrm:
    bind: $SNAP/usr/share/libdrm

apps:
  supertuxkart:
    extensions: [gnome]
    command: usr/bin/supertuxkart
    desktop: usr/share/applications/supertuxkart.desktop
    common-id: net.supertuxkart.SuperTuxKart
    environment:
      SUPERTUXKART_DATADIR: $SNAP/usr/share/supertuxkart
    plugs:
    - audio-playback
    - bluetooth-control
    - desktop
    - desktop-legacy
    - joystick
    - network
    - network-bind
    - opengl
    - pulseaudio
    - screen-inhibit-control
    - wayland
    - x11

parts:
  supertuxkart:
    plugin: cmake
    source: https://github.com/supertuxkart/stk-code/releases/download/$SNAPCRAFT_PROJECT_VERSION/SuperTuxKart-$SNAPCRAFT_PROJECT_VERSION-src.tar.gz
    override-pull: |
      craftctl default
      sed -i 's|^Icon=.*|Icon=/usr/share/icons/hicolor/128x128/apps/supertuxkart.png|' data/supertuxkart.desktop
    parse-info: [usr/share/metainfo/net.supertuxkart.SuperTuxKart.metainfo.xml]
    cmake-parameters:
    - -DCMAKE_INSTALL_PREFIX=/usr
    - -DENABLE_WAYLAND_DEVICE=ON
    - -DBUILD_RECORDER=OFF
    build-environment:
    - CFLAGS: -O2 -pipe
    - CXXFLAGS: -O2 -pipe
    build-packages:
    - curl
    - libbluetooth-dev
    - libcurl4-openssl-dev
    - libfreetype-dev
    - libfribidi-dev
    - libharfbuzz-dev
    - libjpeg-dev
    - libogg-dev
    - libopenal-dev
    - libpng-dev
    - libpulse-dev
    - libsdl2-dev
    - libshaderc-dev
    - libssl-dev
    - libvorbis-dev
    - libxrandr-dev
    - libwayland-dev
    - libxkbcommon-dev
    - subversion
    - zlib1g-dev
    stage-packages:
    - libbluetooth3
      # - libcurl4
      # - libdb5.3
      # - libfreetype6
      # - libfribidi0
      # - libharfbuzz0b
      # - libjpeg8
      # - libogg0
    - libopenal1
      # - libpng16-16
      # - libpulse0
    - libsdl2-2.0-0
    - libshaderc1
    - libsndio7.0
      # - libssl3
      # - libvorbis0a
      # - libvorbisfile3
      # - libxrandr2
      # - libwayland-client0
      # - libwayland-cursor0
      # - libxkbcommon0
      # - zlib1g
