name: supertuxkart
version: '1.0'
adopt-info: supertuxkart
icon: supertuxkart.png

grade: stable
confinement: strict
base: core18

apps:
  supertuxkart:
    command: desktop-launch libopenh264-launch $SNAP/usr/bin/supertuxkart
    desktop: usr/share/applications/supertuxkart.desktop
    environment:
      SUPERTUXKART_DATADIR: $SNAP/usr/share/supertuxkart
    plugs:
    - desktop
    - joystick
    - network
    - network-bind
    - opengl
    - pulseaudio
    - wayland
    - x11

layout:
  /etc/asound.conf:
    bind-file: $SNAP/etc/alsa.conf
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib

parts:
  alsa:
    source: https://github.com/diddledan/snapcraft-alsa.git
    plugin: nil
    override-pull: |
      cat > alsa.conf <<EOF
      pcm.!default {
        type pulse
        fallback "sysdefault"
        hint {
          show on
          description "Default ALSA Output (currently PulseAudio Sound Server)"
        }
      }
      ctl.!default {
        type pulse
        fallback "sysdefault"
      }
      EOF
    override-build: |
      snapcraftctl build
      install -m644 -D -t $SNAPCRAFT_PART_INSTALL/etc alsa.conf
    build-packages:
    - libasound2-dev
    stage-packages:
    - libasound2
    - libasound2-plugins

  desktop-glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
    build-packages:
    - libglib2.0-dev
    stage-packages:
    - libglib2.0-bin

  libopenh264-helper:
    source: libopenh264-helper
    source-subdir: libopenh264
    plugin: make
    stage-packages:
    - bzip2
    - curl
    prime:
    - bin/bunzip2
    - bin/libopenh264-launch
    - usr/bin/curl
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libasn1*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libcurl-gnutls*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libgssapi.so*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libhcrypto*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libheimbase*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libheimntlm*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libhx509*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/liblber*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libldap*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libroken*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/librtmp*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libsasl2*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libwind*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/sasl2

  libopenh264-library:
    plugin: make
    make-parameters:
    - PREFIX=/usr
    source: https://github.com/cisco/openh264/archive/v1.8.0.tar.gz
    build-packages:
    - g++
    - libasound-dev
    - libpulse-dev
    - nasm
    stage-packages:
    - libasound2
    - libpulse0
    override-build: |
      snapcraftctl build
      find $SNAPCRAFT_PART_INSTALL/usr/lib/pkgconfig -name "*openh264*.pc" -exec \
        sed -i "s|/usr/include|$SNAPCRAFT_STAGE/usr/include|g;s|/usr/lib|$SNAPCRAFT_STAGE/usr/lib|g" '{}' \;
    prime:
    - lib/libjson-c*
    - lib/libwrap*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libasound*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libasyncns*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libFLAC*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpulse*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libsndfile*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvorbisenc*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
    - usr/local/lib/libopenh264.so*

  libopenglrecorder:
    after: [libopenh264-library]
    plugin: cmake
    source: https://github.com/Benau/libopenglrecorder.git
    source-depth: 1
    configflags:
    - -DCMAKE_INSTALL_PREFIX=/usr
    build-packages:
    - libturbojpeg0-dev
    - libogg-dev
    - libpulse-dev
    - libvorbis-dev
    - libvpx-dev
    stage-packages:
    - libturbojpeg
    - libogg0
    - libpulse0
    - libvorbisenc2
    - libvpx5

  supertuxkart:
    after:
    - libopenglrecorder
    - libopenh264-library
    plugin: cmake
    source: https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/$SNAPCRAFT_PROJECT_VERSION/supertuxkart-$SNAPCRAFT_PROJECT_VERSION-src.tar.xz
    override-build: |
      sed -i 's|Icon=.*|Icon=${SNAP}/usr/share/icons/hicolor/128x128/apps/supertuxkart.png|' ../src/data/supertuxkart.desktop
      snapcraftctl build
    configflags:
    - -DCMAKE_INSTALL_PREFIX=/usr
    - -DENABLE_WAYLAND_DEVICE=ON
    parse-info: [usr/share/metainfo/supertuxkart.appdata.xml]
    build-packages:
    - libbluetooth-dev
    - libcurl4-openssl-dev
    - libegl1-mesa-dev
    - libfreetype6-dev
    - libfribidi-dev
    - libgl1-mesa-dev
    - libjpeg-dev
    - libogg-dev
    - libopenal-dev
    - libpng-dev
    - libpulse-dev
    - libssl-dev
    - libvorbis-dev
    - libxrandr-dev
    - libwayland-dev
    - libxkbcommon-dev
    - subversion
    - zlib1g-dev
    stage-packages:
    - libbluetooth3
    - libcurl4
    - libdb5.3
    - libfreetype6
    - libfribidi0
    - libgl1-mesa-glx
    - libjpeg8
    - libogg0
    - libopenal1
    - libpng16-16
    - libpulse0
    - libssl1.1
    - libvorbis0a
    - libvorbisfile3
    - libxrandr2
    - libwayland-client0
    - libwayland-cursor0
    - libwayland-egl1-mesa
    - libxkbcommon0
    - zlib1g
    prime:
    - lib
    - usr/bin/supertuxkart
    - usr/lib
    - -usr/lib/gcc
    - -usr/lib/sasl2
    - usr/share/applications
    - usr/share/icons
    - usr/share/metainfo
    - usr/share/pixmaps
    - usr/share/supertuxkart
    - usr/share/X11
